@startuml Graph++ Class Diagram
skinparam {
    classAttributeIconSize 0
    RoundCorner 10
}
package "C++ library" {
    class Graph {
        +name : string
        #vertices : list<Vertex>
        #edges : list<Edge>
        +addVertex(Vertex vertex) : void
        +removeVertex(Vertex vertex) : void
        +addEdge(Vertex vertex, Vertex vertex) : void
        +removeEdge(Edge edge) : void
        +isEulerian() : boolean
        +isHamiltonian() : boolean
        +isConnected() : boolean
        +isStronglyConnected() : boolean
        +Graph() : Graph
    }

    class Edge {
        +source : Vertex
        +target : Vertex
        +weight : int = 1
        +Edge(Vertex source, Vertex target) : Edge
    }

    class Vertex{
        +Vertex() : Vertex
    }

    Vertex "2" -l-o "0..*" Edge
    Edge "0..*" --l--* "1" Graph
    Vertex "0..* " -l-* "1" Graph
}

package "GUI related classes"{
    class DisplayableVertex {
        +name : string = ""
        +x : float
        +y : float
        +textColor : QColor
        +backgroundColor : QColor
        +borderColor : QColor
    }
    class DisplayableGraph {
        +name : string = ""
    }
    class DisplayableEdge {
        +name : string = ""
        +textColor : QColor
        +borderColor : QColor
    }

}



Vertex <|-d- DisplayableVertex
Edge <|-d- DisplayableEdge
Graph <|-d- DisplayableGraph




@enduml